---
title: "Week 10"
author: "Megha S"
date: "July 09, 2019"
output: html_document
---

### K-Means Clustering

```{r}
# Demonstrating how the K-means algorithm works
set.seed(1234)
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))

```

### Using the kmeans() function

```{r}
# The kmeans() function in R implements the K-means algorithm and can be found in the stats package
dataFrame <- data.frame(x, y)
kmeansObj <- kmeans(dataFrame, centers = 3)
names(kmeansObj)

# We can see which cluster each data point got assigned to by looking at the cluster element of the list returned by the kmeans() function
kmeansObj$cluster

```

### Building heatmaps from K-means solutions

```{r}
# A heat map or image plot is sometimes a useful way to visualize matrix or array data
set.seed(1234)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
kmeansObj <- kmeans(dataMatrix, centers = 3)

# Making an image plot using the K-means clusters
par(mfrow = c(1, 2))
image(t(dataMatrix)[, nrow(dataMatrix):1], yaxt = "n", main = "Original Data")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yaxt = "n", main = "Clustered Data")

```
