---
title: "Week 11"
author: "Megha S"
date: "July 16, 2019"
output: html_document
---

### Principal Component Analysis in R - PCA is used to extract data with many variables and create visualizations to display that data
#### Compute the Principal Components

```{r}
# PCA works best with numerical data. You will also set two arguments, center and scale, to be TRUE. Then you can have a peek at your PCA object with summary()
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
summary(mtcars.pca)

# Calling str() to have a look at your PCA object
str(mtcars.pca)

```

### Plotting PCA

```{r}
# We will make a biplot, which includes both the position of each sample in terms of PC1 and PC2 and also will show you how the initial variables map onto this
library(devtools)
install_github("vqv/ggbiplot")

# Calling ggbiplot on your PCA
library(ggbiplot)
ggbiplot(mtcars.pca)

# Providing an argument to ggbiplot
ggbiplot(mtcars.pca, labels=rownames(mtcars))

```

### Interpreting the results

```{r}
# Making a list of info, then pass it to the groups argument of ggbiplot
mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))

ggbiplot(mtcars.pca,ellipse=TRUE,  labels=rownames(mtcars), groups=mtcars.country)

# Asking ggbiplot to plot these other components, by using the choices argument. Having a look at PC3 and PC4
ggbiplot(mtcars.pca,ellipse=TRUE,choices=c(3,4), labels=rownames(mtcars), groups=mtcars.country)

```

### Graphical parameters with ggbiplot

```{r}
# Altering biplots by adding a circle to the center of the dataset
ggbiplot(mtcars.pca,ellipse=TRUE,circle=TRUE, labels=rownames(mtcars), groups=mtcars.country)

# Scaling the samples (obs.scale) and the variables (var.scale)
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country)

# Removing the arrows using var.axes
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,var.axes=FALSE,   labels=rownames(mtcars), groups=mtcars.country)

```

### Customize ggbiplot

```{r}
# Customizing ggbiplot to alter your biplots
# Specify the colours to use for the groups with scale_colour_manual()
# Add a title with ggtitle()
# Specify the minimal() theme
# Move the legend with theme()
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country) +
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "dark blue"))+
  ggtitle("PCA of mtcars dataset")+
  theme_minimal()+
  theme(legend.position = "bottom")

```

### Adding a new sample

```{r}
# Adding a new sample to mtcars, creating mtcarsplus, then repeat the analysis
spacecar <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)

mtcarsplus <- rbind(mtcars, spacecar)
mtcars.countryplus <- c(mtcars.country, "Jupiter")

mtcarsplus.pca <- prcomp(mtcarsplus[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

ggbiplot(mtcarsplus.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample added")+
  theme_minimal()+
  theme(legend.position = "bottom")
```

### Project a new sample onto the original PCA

```{r}
# Scaling the values for spacecar in relation to the PCA's center (mtcars.pca$center). Then applying the rotation of the PCA matrix to the spacecar sample
s.sc <- scale(t(spacecar[c(1:7,10,11)]), center= mtcars.pca$center)
s.pred <- s.sc %*% mtcars.pca$rotation


mtcars.plusproj.pca <- mtcars.pca
mtcars.plusproj.pca$x <- rbind(mtcars.plusproj.pca$x, s.pred)


ggbiplot(mtcars.plusproj.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample projected")+
  theme_minimal()+
  theme(legend.position = "bottom")

```
